export const metadata = {
    title: 'Blogs List',
    description: 'Generated by tedvkieu',
};

export default function BlogLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <>{children}</>;
}
