export const metadata = {
    title: 'View Detail Blog',
    description: 'Generated by tedvkieu',
};

export default function ViewDetailLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <>{children}</>;
}
